version: '2'
services:
    # nginx
    nginx:
        container_name: "nginx"
        network_mode: "bridge"
        image: "nginx"
        links:
            - "php7.4.4"
            - "php5.6"
        restart: "always"
        volumes:
            - "./wwwroot:/nginx/data"
            - "./nginx/log:/nginx/log"
            - "./nginx/conf.d:/nginx/conf.d"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "8080:80"
            
    # php7.4.4
    php7.4.4:
        container_name: "php7.4.4"
        network_mode: "bridge"
        image: "gongwen/php:7.4.4"
        links:
            - "mysql56"
            - "mysql57"
        restart: "always"
        volumes:
            - "./wwwroot:/nginx/data"

    # php5.6
    php5.6:
        container_name: "php5.6"
        network_mode: "bridge"
        image: "gongwen/php:php5.6"
        links:
            - "mysql56"
            - "mysql57"
        restart: "always"
        volumes:
            - "./php5.6/php.ini:/usr/local/etc/php/php.ini"
            - "./php5.6/conf.d:/usr/local/etc/php/conf.d"
            - "./wwwroot:/nginx/data"

    # mysql5.6
    mysql56:
        container_name: "mysql56"
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            TZ: "Asia/Shanghai" 
        image: "mysql:5.6"
        restart: "always"
        volumes:
            - "./mysql5.6/data:/var/lib/mysql"
            - "./mysql5.6/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./mysql5.6/logs:/logs"
            - "./mysql5.6/init:/docker-entrypoint-initdb.d"
        ports:
            - "13356:3306"

    # mysql5.7        
    mysql57:
        container_name: "mysql57"
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            TZ: "Asia/Shanghai" 
        image: "mysql:5.7"
        restart: "always"
        volumes:
            - "./mysql5.7/data:/var/lib/mysql"
            - "./mysql5.7/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./mysql5.7/logs:/logs"
            - "./mysql5.7/init:/docker-entrypoint-initdb.d"
        ports:
            - "13357:3306"
