version: '3.4'

x-env:
    &hosts
        - test.com:172.0.0.10
        - www.test.com:127.0.0.10

services:
    # nginx
    nginx:
        container_name: "nginx"
        image: "${NGINX}"
        links:
            - "php7.4"
            - "php5.6"
        restart: "always"
        volumes:
            - "${WWWROOT}:/nginx/data"
            - "./nginx/log:/nginx/log"
            - "./nginx/conf.d:/nginx/conf.d"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "${PORT80}"
            - "${PORT443}"
        networks:
            default:
                ipv4_address: 172.0.0.10
        
    # php7.4.4
    php7.4:
        container_name: "php7.4.4"
        image: "${PHP74}"
        links:
            - "mysql56"
            - "mysql57"
        restart: "always"
        volumes:
            - "./php7.4.4/php.ini:/usr/local/etc/php/php.ini"
            - "./php7.4.4/conf.d:/usr/local/etc/php/conf.d"
            - "${WWWROOT}:/nginx/data"
        extra_hosts: 
            extra_hosts: *hosts 

    # php5.6
    php5.6:
        container_name: "php5.6"
        image: "${PHP56}"
        links:
            - "mysql56"
            - "mysql57"
        restart: "always"
        volumes:
            - "./php5.6/php.ini:/usr/local/etc/php/php.ini"
            - "./php5.6/conf.d:/usr/local/etc/php/conf.d"
            - "${WWWROOT}:/nginx/data"
        extra_hosts: *hosts    

    # mysql5.6
    mysql56:
        container_name: "mysql56"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL5_6_ROOT_PASSWORD}"
            TZ: "${TZ}"
        image: "${MYSQL56}"
        restart: "always"
        volumes:
            - "./mysql5.6/data:/var/lib/mysql"
            - "./mysql5.6/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./mysql5.6/logs:/logs"
            - "./mysql5.6/init:/docker-entrypoint-initdb.d"
        ports:
            - "${MYSQL5_6_PORT3306}"

    # mysql5.7
    mysql57:
        container_name: "mysql57"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL5_7_ROOT_PASSWORD}"
            TZ: "${TZ}" 
        image: "${MYSQL57}"
        restart: "always"
        volumes:
            - "./mysql5.7/data:/var/lib/mysql"
            - "./mysql5.7/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./mysql5.7/logs:/logs"
            - "./mysql5.7/init:/docker-entrypoint-initdb.d"
        ports:
            - "${MYSQL5_7_PORT3306}"

networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24            
